/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DesignRouteImport } from './routes/design'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as GrafoRouteImport } from './routes/grafo'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as ProbeRouteImport } from './routes/probe'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const GrafoRoute = GrafoRouteImport.update({
  id: '/grafo',
  path: '/grafo',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeRoute = ProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/busca': typeof BuscaRoute
  '/captura': typeof CapturaRoute
  '/chat': typeof ChatRoute
  '/colecao': typeof ColecaoRoute
  '/comparar': typeof CompararRoute
  '/config': typeof ConfigRoute
  '/datasets': typeof DatasetsRoute
  '/design': typeof DesignRoute
  '/equipe': typeof EquipeRoute
  '/fluxos': typeof FluxosRoute
  '/grafo': typeof GrafoRoute
  '/graphql': typeof GraphqlRoute
  '/marketplace': typeof MarketplaceRoute
  '/precos': typeof PrecosRoute
  '/probe': typeof ProbeRoute
  '/qualidade': typeof QualidadeRoute
  '/revisao': typeof RevisaoRoute
  '/roi': typeof RoiRoute
  '/snapshots': typeof SnapshotsRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/webhooks': typeof WebhooksRoute
  '/workers': typeof WorkersRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/busca': typeof BuscaRoute
  '/captura': typeof CapturaRoute
  '/chat': typeof ChatRoute
  '/colecao': typeof ColecaoRoute
  '/comparar': typeof CompararRoute
  '/config': typeof ConfigRoute
  '/datasets': typeof DatasetsRoute
  '/design': typeof DesignRoute
  '/equipe': typeof EquipeRoute
  '/fluxos': typeof FluxosRoute
  '/grafo': typeof GrafoRoute
  '/graphql': typeof GraphqlRoute
  '/marketplace': typeof MarketplaceRoute
  '/precos': typeof PrecosRoute
  '/probe': typeof ProbeRoute
  '/qualidade': typeof QualidadeRoute
  '/revisao': typeof RevisaoRoute
  '/roi': typeof RoiRoute
  '/snapshots': typeof SnapshotsRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/webhooks': typeof WebhooksRoute
  '/workers': typeof WorkersRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/busca': typeof BuscaRoute
  '/captura': typeof CapturaRoute
  '/chat': typeof ChatRoute
  '/colecao': typeof ColecaoRoute
  '/comparar': typeof CompararRoute
  '/config': typeof ConfigRoute
  '/datasets': typeof DatasetsRoute
  '/design': typeof DesignRoute
  '/equipe': typeof EquipeRoute
  '/fluxos': typeof FluxosRoute
  '/grafo': typeof GrafoRoute
  '/graphql': typeof GraphqlRoute
  '/marketplace': typeof MarketplaceRoute
  '/precos': typeof PrecosRoute
  '/probe': typeof ProbeRoute
  '/qualidade': typeof QualidadeRoute
  '/revisao': typeof RevisaoRoute
  '/roi': typeof RoiRoute
  '/snapshots': typeof SnapshotsRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/webhooks': typeof WebhooksRoute
  '/workers': typeof WorkersRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/busca'
    | '/captura'
    | '/chat'
    | '/colecao'
    | '/comparar'
    | '/config'
    | '/datasets'
    | '/design'
    | '/equipe'
    | '/fluxos'
    | '/grafo'
    | '/graphql'
    | '/marketplace'
    | '/precos'
    | '/probe'
    | '/qualidade'
    | '/revisao'
    | '/roi'
    | '/snapshots'
    | '/stats'
    | '/timeline'
    | '/webhooks'
    | '/workers'
    | '/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/busca'
    | '/captura'
    | '/chat'
    | '/colecao'
    | '/comparar'
    | '/config'
    | '/datasets'
    | '/design'
    | '/equipe'
    | '/fluxos'
    | '/grafo'
    | '/graphql'
    | '/marketplace'
    | '/precos'
    | '/probe'
    | '/qualidade'
    | '/revisao'
    | '/roi'
    | '/snapshots'
    | '/stats'
    | '/timeline'
    | '/webhooks'
    | '/workers'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/busca'
    | '/captura'
    | '/chat'
    | '/colecao'
    | '/comparar'
    | '/config'
    | '/datasets'
    | '/design'
    | '/equipe'
    | '/fluxos'
    | '/grafo'
    | '/graphql'
    | '/marketplace'
    | '/precos'
    | '/probe'
    | '/qualidade'
    | '/revisao'
    | '/roi'
    | '/snapshots'
    | '/stats'
    | '/timeline'
    | '/webhooks'
    | '/workers'
    | '/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuscaRoute: typeof BuscaRoute
  CapturaRoute: typeof CapturaRoute
  ChatRoute: typeof ChatRoute
  ColecaoRoute: typeof ColecaoRoute
  CompararRoute: typeof CompararRoute
  ConfigRoute: typeof ConfigRoute
  DatasetsRoute: typeof DatasetsRoute
  DesignRoute: typeof DesignRoute
  EquipeRoute: typeof EquipeRoute
  FluxosRoute: typeof FluxosRoute
  GrafoRoute: typeof GrafoRoute
  GraphqlRoute: typeof GraphqlRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PrecosRoute: typeof PrecosRoute
  ProbeRoute: typeof ProbeRoute
  QualidadeRoute: typeof QualidadeRoute
  RevisaoRoute: typeof RevisaoRoute
  RoiRoute: typeof RoiRoute
  SnapshotsRoute: typeof SnapshotsRoute
  StatsRoute: typeof StatsRoute
  TimelineRoute: typeof TimelineRoute
  WebhooksRoute: typeof WebhooksRoute
  WorkersRoute: typeof WorkersRoute
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grafo': {
      id: '/grafo'
      path: '/grafo'
      fullPath: '/grafo'
      preLoaderRoute: typeof GrafoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe': {
      id: '/probe'
      path: '/probe'
      fullPath: '/probe'
      preLoaderRoute: typeof ProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuscaRoute: BuscaRoute,
  CapturaRoute: CapturaRoute,
  ChatRoute: ChatRoute,
  ColecaoRoute: ColecaoRoute,
  CompararRoute: CompararRoute,
  ConfigRoute: ConfigRoute,
  DatasetsRoute: DatasetsRoute,
  DesignRoute: DesignRoute,
  EquipeRoute: EquipeRoute,
  FluxosRoute: FluxosRoute,
  GrafoRoute: GrafoRoute,
  GraphqlRoute: GraphqlRoute,
  MarketplaceRoute: MarketplaceRoute,
  PrecosRoute: PrecosRoute,
  ProbeRoute: ProbeRoute,
  QualidadeRoute: QualidadeRoute,
  RevisaoRoute: RevisaoRoute,
  RoiRoute: RoiRoute,
  SnapshotsRoute: SnapshotsRoute,
  StatsRoute: StatsRoute,
  TimelineRoute: TimelineRoute,
  WebhooksRoute: WebhooksRoute,
  WorkersRoute: WorkersRoute,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
